spring:
  application:
    name: migration-example
  datasource:
    url: "jdbc:postgresql://localhost:5432/migration-example?currentSchema=migration-example"
    username: me
    password: me
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    liquibase-schema: migration-example

